### ISSUE TITLE
crash report

### ISSUE THREAD

**Issue by schriftgestalt** [eweracs/ShowHTLetterspacerAreas#6]
```
  File "GlyphsApp/GlyphsApp/plugins.py", line 1411, in raiseException_

  File "GlyphsApp/GlyphsApp/plugins.py", line 1282, in drawForegroundForInactiveLayer_options_

  File "plugin.py", line 116, in inactiveLayerForeground
    self.create_polygons(layer)

  File "plugin.py", line 97, in create_polygons
    new_layer.completeBezierPath.fill()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "GlyphsApp/GlyphsApp/__init__.py", line 9186, in <lambda>

AttributeError: 'NoneType' object has no attribute 'autorelease'
```
App:3.2.3-3260 Plugin:1.2-1 System:15.1.0

**Comment by schriftgestalt** [comment]
I got another one:
```
Traceback (most recent call last):
 
  File "GlyphsApp/GlyphsApp/plugins.py", line 1413, in raiseException_
 
  File "GlyphsApp/GlyphsApp/plugins.py", line 1284, in drawForegroundForInactiveLayer_options_
 
  File "plugin.py", line 116, in inactiveLayerForeground
    self.create_polygons(layer)
 
  File "plugin.py", line 97, in create_polygons
    new_layer.completeBezierPath.fill()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 
AttributeError: 'NoneType' object has no attribute 'fill'
``` 
App:3.3-3331 Plugin:1.2-1 System:14.7.3
